name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install tesseract
      run: sudo apt-get install libleptonica-dev libtesseract-dev clang tesseract-ocr-eng
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --no-default-features --verbose
    - name: Run tests
      run: cargo test --verbose
