name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Deps
      run: |
        sudo apt update
        sudo apt install build-essential
        sudo apt install curl
        sudo apt install pkg-config
        sudo apt install clang
        sudo apt install libleptonica-dev
        sudo apt install libtesseract-dev
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
